version: '3.1'
services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
  web:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    volumes:
      - ./html:/usr/local/apache2/htdocs/